import { createActions } from 'redux-actions';

export default createActions(
  'INIT_ASYNCLATEST',
  'REDUCER_CHANGE',
  'REDUCER_BUSY',

  'VIEW_CHANGE',

  'READWELCOME_ASYNCLATEST',
  'READSQL_ASYNCLATEST',
  'READLOG_ASYNCLATEST',
  'READTEST_ASYNCLATEST',
  'EXPORTSVG_ASYNCLATEST'
);


// 'PATTERN_D_ASYNC',
// 'PATTERN_D_THROUGH',
// 'PATTERN_D_INC_ASYNCLATEST',
// 'SHORTCUT_INC'
