import { createActions } from 'redux-actions';

export default createActions(
  'REDUCER_CHANGE',

  'VIEW_CHANGE',

  'READWELCOM_ASYNCLATEST',
  'READSQL_ASYNCLATEST',
  'READLOG_ASYNCLATEST',
  'READTEST_ASYNCLATEST'
);


// 'PATTERN_D_ASYNC',
// 'PATTERN_D_THROUGH',
// 'PATTERN_D_INC_ASYNCLATEST',
// 'SHORTCUT_INC'
